spring:
  application:
    name: read_book_online

  datasource:
    url: jdbc:postgresql://dpg-d04dc4juibrs73b021ag-a.oregon-postgres.render.com:5432/book_online_db_962g
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          timeout: 30000

  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
      provider:
        google:
          authorization-uri: https://accounts.google.com/o/oauth2/auth
          token-uri: https://oauth2.googleapis.com/token
          user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    from: ${EMAIL_USERNAME}

app:
  security:
    jwt:
      privateKey: ${JWT_PRIVATE_KEY}
      prefix: Bearer
      authHeader: Authorization
      keyExpiresAt: 3600000
      refreshKey: ${JWT_REFRESH_KEY}
      refreshExpiresAt: 604800000

endpoint:
  confirmUser: ${APP_URL}/api/v1/auth/confirm

momo:
  partnerCode: ${MOMO_PARTNER_CODE}
  accessKey: ${MOMO_ACCESS_KEY}
  secretKey: ${MOMO_SECRET_KEY}
  endpoint: https://test-payment.momo.vn/v2/gateway/api/create
  ipnUrl: ${APP_URL}/api/v1/ipn
  redirectUrl: ${APP_URL}/api/v1/redirect

ghn:
  token: ${GHN_TOKEN}
  apiUrl:
    getProvinces: https://online-gateway.ghn.vn/shiip/public-api/master-data/province
    getDistrict: https://online-gateway.ghn.vn/shiip/public-api/master-data/district
    getWard: https://online-gateway.ghn.vn/shiip/public-api/master-data/ward

openapi:
  service:
    api-docs: api-service
    server: ${APP_URL}
    title: API Service
    version: 1.0.0

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
    com.example: DEBUG
